### PR TITLE
Fix mfem4.8 about petsc config

### LINKED ISSUE #4793: Error when config mfem4.8 about petsc
Previously, I successfully compiled on MFEM 4.7 version. I migrated my previous settings to version 4.8 and attempted to link to the previously compiled dependent libraries. An error occurred during the CMake configuration stage. Specifically, when running multipass_test_00_petsc_works_*, a linking error occurred: "undefined reference to symbol feenableexcept@@GLIBC_2.2.5".

I carefully compared the compilation records of the same phase (compilation of test programs in config) and found that the compilation of 4.8 lacks many dynamic link libraries, such as mpi/libldl/libm/libstdc++ etc..

In `FindPETSc.cmake`, about line 310, `petsc_libs_external` is right, but `petsc_libraries_external` missing a lot. So it seems that there is something wrong in `resolve_libraries`.

In `ResolveCompilePaths.cmake`, about line 96, `set(_lib "NOTFOUND" CACHE FILEPATH "Cleared" FORCE)`, the variable `_lib` is not cleared between iterations. If I change this line to `set(_lib "NOTFOUND")`, I can pass the config! It is strange that all works well in 4.7.

I notice that neither FindPETSc.cmake nor ResolveCompilePaths.cmake changed between 4.7 and 4.8. And I run same cmd to config in same terminal with same cmake. What could be the reason for such differences? 

I always use cmake 3.25. Does this problem is caused by `cmake_minimun_required` changing from 3.8 to 3.12? Maybe it affects the police of `set`?

### PR DESCRIPTION
**Pull request by chapman39**
Fixes #4793

Though, maybe there is a more robust fix that could be implemented instead. See issue for details.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4806](https://github.com/mfem/mfem/pull/4806) | @chapman39 | @v-dobrev | @helloworld922 + @v-dobrev + @stefanozampini | 4/16/25 | 5/2/25 | 5/7/25 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by chapman39** [comment]
@luanmingyi let me know if this resolves your issues as well

**Comment by v-dobrev** [comment]
An alternative may be this patch (I have not tried it yet):
```diff
diff --git a/config/cmake/modules/ResolveCompilerPaths.cmake b/config/cmake/modules/ResolveCompilerPaths.cmake
index b0751adada..06f2b90152 100644
--- a/config/cmake/modules/ResolveCompilerPaths.cmake
+++ b/config/cmake/modules/ResolveCompilerPaths.cmake
@@ -93,7 +93,7 @@ macro (RESOLVE_LIBRARIES LIBS LINK_LINE)
         set (_directory_list ${_directory_list} ${libpath})
         set (token ${libname})
       endif (token MATCHES "^/")
-      set (_lib "NOTFOUND" CACHE FILEPATH "Cleared" FORCE)
+      set (_lib "NOTFOUND")
       find_library (_lib ${token} HINTS ${_directory_list} ${_root})
       if (_lib)
        string (REPLACE "//" "/" _lib ${_lib})
@@ -103,7 +103,6 @@ macro (RESOLVE_LIBRARIES LIBS LINK_LINE)
       endif (_lib)
     endif (token MATCHES "-L([^\" ]+|\"[^\"]+\")")
   endforeach (token)
-  set (_lib "NOTFOUND" CACHE INTERNAL "Scratch variable" FORCE)
   # only the LAST occurrence of each library is required since there should be no circular dependencies
   if (_libs_found)
     list (REVERSE _libs_found)
```

**Comment by v-dobrev** [comment]
The thing with `find_library(_lib ...)` is that it will put `_lib` in the cache, so we may want to simply remove it from the cache with `unset(_lib CACHE)`, after using its value.

**Comment by chapman39** [comment]
applied recommended diff instead of updating policy

**Comment by luanmingyi** [comment]
@chapman39 Both modifying the policy and removing the CACHE can solve my problem.

File: config/cmake/modules/ResolveCompilerPaths.cmake [hunk 1]
```diff
@@ -103,7 +103,6 @@ macro (RESOLVE_LIBRARIES LIBS LINK_LINE)
       endif (_lib)
     endif (token MATCHES "-L([^\" ]+|\"[^\"]+\")")
   endforeach (token)
-  set (_lib "NOTFOUND" CACHE INTERNAL "Scratch variable" FORCE)
```
Comment (v-dobrev) [inline config/cmake/modules/ResolveCompilerPaths.cmake:106]: It may be good to remove `_lib` from the cache variables with `unset(_lib CACHE)`.

Comment (chapman39) [reply config/cmake/modules/ResolveCompilerPaths.cmake:106]: well since lib isn't being set as a cache variable anymore, is that necessary?

`set (_lib "NOTFOUND")`

Comment (v-dobrev) [reply config/cmake/modules/ResolveCompilerPaths.cmake:106]: The call to `find_library(_lib ...)` makes `_lib` a cache entry, see e.g. https://cmake.org/cmake/help/v3.12/command/find_library.html.

Comment (chapman39) [reply config/cmake/modules/ResolveCompilerPaths.cmake:106]: oh good to know. ill add that then.

**Review by v-dobrev — APPROVED** [review]

**Review by helloworld922 — APPROVED** [review]
