### ISSUE TITLE
Building Parallel MFEM

### ISSUE THREAD

**Issue by merthidayetoglu** [mfem/mfem#2688]
Hello, I have gone through the exact steps in order with exact versions in the https://mfem.org/building/ page, however, I obtain the error I pasted below. Can you please help me to build MFEM parallel examples?

merth@thetalogin4:~/MFEM/mfem-3.4> make parallel -j
make -f makefile config MFEM_USE_MPI=YES MFEM_DEBUG=NO \
   
make[1]: Entering directory '/gpfs/mira-home/merth/MFEM/mfem-3.4'
make -C config all
make[2]: Entering directory '/gpfs/mira-home/merth/MFEM/mfem-3.4/config'
mpicxx -I../../hypre-2.10.0b/src/hypre/include get_hypre_version.cpp -o get_hypre_version
get_hypre_version.cpp:12:10: fatal error: HYPRE_config.h: No such file or directory
 #include "HYPRE_config.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [makefile:47: get_hypre_version] Error 1
make[2]: Leaving directory '/gpfs/mira-home/merth/MFEM/mfem-3.4/config'
make[1]: *** [makefile:459: local-config] Error 2
make[1]: Leaving directory '/gpfs/mira-home/merth/MFEM/mfem-3.4'
make: *** [makefile:366: parallel] Error 2

**Comment by tzanio** [comment]
Hi @merthidayetoglu,

It would appear that your hypre build did not work, can you double check that `./configure` followed by `make` succeeded in `../../hypre-2.10.0b/src/`.

Note also that you can use the latest versions of hypre and mfem instead of 2.10.0b and 3.4.

Tzanio

**Comment by v-dobrev** [comment]
Hi @merthidayetoglu,

We should probably fix the instructions: if one follows them literally, mfem-3.4 uses `../hypre-2.10.0b` by default whereas the instructions create a link `../hypre` which is what newer mfem versions use by default. This is probably the reason for the failure you observed.

If you switch to the latest mfem release (mfem-4.3) then the latest hypre release that you can use is hypre-2.22.0, I think (later versions of hypre have small changes that do not work with mfem-4.3 -- these issues are addressed in mfem's `master` branch).

If you clone the latest default (`master`) branches of both mfem and hypre from github -- that should work too.
