### ISSUE TITLE
SuperLU_DIST version 5 and 6 support issue

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#4221]
It appears that the current version of MFEM cannot compile with versions 5.1.3 and 6.3.1 of SuperLU_DIST. I have not tested other minor version numbers.

In 5.1.3 the error is:
```
linalg/superlu.cpp:544:16: error: use of undeclared identifier 'ZeroLblocks'
               ZeroLblocks(grid->iam, APtr_->GetGlobalNumColumns(),
               ^
linalg/superlu.cpp:546:16: error: use of undeclared identifier 'ZeroUblocks'
               ZeroUblocks(grid->iam, APtr_->GetGlobalNumColumns(),
               ^
```

In 6.3.1 these functions are both redefined using macros but only one of them is set to a valid function name apparently:
```
linalg/superlu.cpp:546:16: error: use of undeclared identifier 'dZeroUblocks'; did you mean 'dZeroLblocks'?
               ZeroUblocks(grid->iam, APtr_->GetGlobalNumColumns(),
               ^~~~~~~~~~~
               dZeroLblocks
linalg/superlu.cpp:35:21: note: expanded from macro 'ZeroUblocks'
#define ZeroUblocks dZeroUblocks
                    ^
```

If we intend to continue support for these older versions we may need to dig out the old implementations or find some workaround.

**Comment by sebastiangrimberg** [comment]
Version 6.0 came out almost 7 years ago, and 7.0 came out 3 years ago. I think it should be fine to make the update and require SuperLU_DIST >= 7.0. Do others agree?

**Comment by adam-sim-dev** [comment]
Also a suggestion, rename "Superlu" to "superlu_dist"

**Comment by sebastiangrimberg** [comment]
> Also a suggestion, rename "Superlu" to "superlu_dist" in mfem.

Do you mean just in the source code? Like `SuperLUSolver` to `SuperLUDistSolver` or something like that? I'm not sure how valuable such a renaming would be but will let others state their opinions here.

**Comment by adam-sim-dev** [comment]
> > Also a suggestion, rename "Superlu" to "superlu_dist" in mfem.
> 
> 
> 
> Do you mean just in the source code? Like `SuperLUSolver` to `SuperLUDistSolver` or something like that? I'm not sure how valuable such a renaming would be but will let others state their opinions here.

In the souce code and the document. Anyway, superlu and superlu_dist are different solvers as I can see.
