### PR TITLE
Replace `MPI_Session` with `Mpi::Init`

### LINKED ISSUE #2957: MPI_Session is an MPI 4.0 handle
It appears that `MPI_Session` is used in `general/communication.hpp` as a class name. MPI 4.0 added `MPI_Session` as a standard MPI handle type. Spack E4S builds with MPICH versions >= 4.0 fail because of the ambiguity.

https://github.com/mfem/mfem/blob/168b19fc4904dc90e217bef9b5c3f595c4865da2/general/communication.hpp#L90-L104

```
ex1p.cpp(66): error: "MPI_Session" is ambiguous
1 error detected in the compilation of "ex1p.cpp".
makefile:78: recipe for target 'ex1p' failed
make: *** [ex1p] Error 1
make: Leaving directory '/tmp/root/spack-stage/spack-stage-mfem-4.3.0-eh3uxmai2x52ienouug4aiftaydipfd6/spack-src/examples'
```

### PR DESCRIPTION
**Pull request by v-dobrev**
In `navier_turbchan.cpp`, switch to `Mpi::Init()` instead of `MPI_Session` similar to all other examples and miniapps.

This should resolve #2957.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3040](https://github.com/mfem/mfem/pull/3040) | @v-dobrev | @tzanio | @jandrej + @tzanio | 5/24/22 | 5/25/22 | 5/27/22 | |

# PR Checklist
    
- [x] Code builds.
- [x] Code passes `make style`.

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by jandrej — APPROVED** [review]
