### ISSUE TITLE
CuDSSSolver does not compile with cuDSS 0.8

### ISSUE THREAD

**Issue by Sbozzolo** [mfem/mfem#5441]
I was working on building MFEM with GPUs with Spack and found that the
`CuDSSSolver` implementation added in #5124 targets the cuDSS 0.7 API and does
not compile against cuDSS 0.8.

A representative error is:

```text
error: use of undeclared identifier 'CUDSS_DATA_COMM'
error: no matching function for call to 'cudssMatrixCreateCsr'
note: candidate function not viable: requires 14 arguments, but 13 were provided
error: no known conversion from 'cudaDataType_t' to 'cudssDataType_t'
```

The relevant breaking changes are the following:

1. `CUDSS_DATA_COMM` was replaced with `CUDSS_DATA_COMM_HOST` and  `CUDSS_DATA_COMM_DEVICE`.

2. `cudssMatrixCreateCsr` gained a datatype argument. cuDSS 0.7 takes one integer datatype followed by the value datatype, but cuDSS 0.8 takes separate `offsetType`, `indexType`, and `valueType` arguments.

3. Matrix datatype parameters changed type. cuDSS 0.8 matrix APIs use `cudssDataType_t` and the `CUDSS_R_*` constants. MFEM currently passes `cudaDataType_t` values such as `CUDA_R_32I` and `CUDA_R_64F`. C++ does not implicitly convert between these enum types. This also affects `cudssMatrixCreateDn`.

4. `cudssDistributedInterface_t` now has separate host and device callbacks.

**Comment by Sbozzolo** [comment]
> ⚠️ This issue has been automatically marked as stale because it has not had any activity in the last month. _If no activity occurs in the next week, it will be automatically closed._ Thank you for your contributions.

I think this issue is valid
