### PR TITLE
Some fixes for hypre v2.26.0

### PR DESCRIPTION
**Pull request by v-dobrev**
These fixes were needed when hypre is built with GPU support.

Also, a few fixes for warnings and a wrong command line argument.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3257](https://github.com/mfem/mfem/pull/3257) | @v-dobrev | @tzanio | @tzanio + @camierjs | 10/18/22 | 10/18/22 | 10/21/22 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]
Thanks for fixing this so quickly @v-dobrev !

File: tests/unit/linalg/test_matrix_hypre.cpp [hunk 1]
```diff
@@ -100,6 +100,7 @@ TEST_CASE("HypreParMatrixAbsMult",  "[Parallel], [HypreParMatrixAbsMult]")
       X0.Randomize(1);
       X1.Randomize(1);
       A->AbsMultTranspose(3.4,Y0,-2.3,X0);
+      Aabs->EnsureMultTranspose();
```
Comment (acfisher) [inline tests/unit/linalg/test_matrix_hypre.cpp:103]: Why can't we put the Ensure call in the MultTranspose method?

**Comment by tzanio** [comment]
Merging in `next` just to speed-up testing -- please continue to review 🙏

**Comment by jwang125** [comment]
I built hypre with `configure --prefix=/g/g90/wang125/software/hypre  --with-cuda` from master. Then, mfem with 
`make config PREFIX=/g/g90/wang125/software/mfem/ MFEM_USE_MPI=YES MFEM_USE_METIS=YES MFEM_USE_METIS_5=YES    MFEM_USE_CUDA=YES  CUDA_ARCH=sm_70 HYPRE_DIR=/g/g90/wang125/software/hypre`. While make -j4 compiles, make examples does not compile. Error:
```
nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_70 -ccbin mpicxx -I.. -I/g/g90/wang125/software/hypre//include -I/g/g90/wang125/software/metis//include ex0p.cpp -o ex0p -L.. -lmfem -L/g/g90/wang125/software/hypre//lib -lHYPRE -lcusparse -lcurand -lcublas -L/g/g90/wang125/software/metis//lib -lmetis -lcusparse -lrt
/g/g90/wang125/software/hypre//lib/libHYPRE.a(IJMatrix_parcsr_device.obj):(.data+0x8e0): undefined reference to `__UnsupportedConditionalExpressionDestruction'
/g/g90/wang125/software/hypre//lib/libHYPRE.a(IJMatrix_parcsr_device.obj):(.toc+0x1c0): undefined reference to `__UnsupportedConditionalExpressionDestruction'
```
Not sure if I did something wrong.

**Comment by v-dobrev** [comment]
@jwang125, I suspect you need to add `--with-gpu-arch="70"` to the hypre config command line.

File: tests/unit/linalg/test_matrix_hypre.cpp (hunk 1 above)
Comment (v-dobrev) [reply tests/unit/linalg/test_matrix_hypre.cpp:103]: That is an option. I was also thinking if we should do that and if there are any big drawbacks to doing that.

This method (`EnsureMultTranspose`) was introduced in #3052, to be similar to the method with the same name in class `SparseMatrix`.

The reasoning for asking the user to explicitly call `EnsureMultTranspose`, if they need the action of the transpose, was to make it more obvious that `SparseMatrix` and `HypreParMatrix` construct and store the transpose in certain cases (e.g. when running on GPU). This was to make it more obvious to users that if they modify the matrix, then they will need to rebuild the transpose too. In the case of `SparseMatrix` this can be done by calling the method `ResetTranspose` whereas for `HypreParMatrix` we did not actually add such method, partially because we rarely, if ever, modify `HypreParMatrix` objects after constructing them.

So we can choose to hide `EnsureMultTranspose` inside `MultTranspose` (and other similar methods like `AddMultTraspose`), however that makes the fact that one needs to delete/rebuild the transpose when modifying the matrix less obvious.

**Comment by jwang125** [comment]
OK. I tried that. Using cuda/11.3 instead of cuda/11.1.  Unfortunately, I still have the same problem with mfem make examples on lassen. If you don't see this, it's probably my problem. I'm on lassen. Will try again later.

File: tests/unit/linalg/test_matrix_hypre.cpp (hunk 1 above)
Comment (acfisher) [reply tests/unit/linalg/test_matrix_hypre.cpp:103]: I see the dilemma.  I think it's best to require it before MultTranspose and put something in the MultTranspose documentation that says you must call EnsureMultTranspose to get it there and ResetTranspose if it is changed.

**Comment by v-dobrev** [comment]
It is possible that hypre's config picks up MPI C/C++/nvcc compilers that are different from the defaults you have loaded with modules. You can see what it finds in the `./configure` output.

**Comment by jwang125** [comment]
Thanks. This solved the problem. No more issues from me.

File: tests/unit/linalg/test_matrix_hypre.cpp (hunk 1 above)
Comment (v-dobrev) [reply tests/unit/linalg/test_matrix_hypre.cpp]: @acfisher, @tzanio, I made the updates as we discussed offline. Take a look and let me know if I missed something.

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Review by liruipeng — APPROVED** [review]
Looks good to me. Thanks!
