### ISSUE TITLE
Error when config mfem4.8 about petsc

### ISSUE THREAD

**Issue by luanmingyi** [mfem/mfem#4793]
Previously, I successfully compiled on MFEM 4.7 version. I migrated my previous settings to version 4.8 and attempted to link to the previously compiled dependent libraries. An error occurred during the CMake configuration stage. Specifically, when running multipass_test_00_petsc_works_*, a linking error occurred: "undefined reference to symbol feenableexcept@@GLIBC_2.2.5".

I carefully compared the compilation records of the same phase (compilation of test programs in config) and found that the compilation of 4.8 lacks many dynamic link libraries, such as mpi/libldl/libm/libstdc++ etc..

In `FindPETSc.cmake`, about line 310, `petsc_libs_external` is right, but `petsc_libraries_external` missing a lot. So it seems that there is something wrong in `resolve_libraries`.

In `ResolveCompilePaths.cmake`, about line 96, `set(_lib "NOTFOUND" CACHE FILEPATH "Cleared" FORCE)`, the variable `_lib` is not cleared between iterations. If I change this line to `set(_lib "NOTFOUND")`, I can pass the config! It is strange that all works well in 4.7.

I notice that neither FindPETSc.cmake nor ResolveCompilePaths.cmake changed between 4.7 and 4.8. And I run same cmd to config in same terminal with same cmake. What could be the reason for such differences? 

I always use cmake 3.25. Does this problem is caused by `cmake_minimun_required` changing from 3.8 to 3.12? Maybe it affects the police of `set`?

**Comment by luanmingyi** [comment]
I carefully compared the compilation records of the same phase (compilation of test programs in config) and found that the compilation of 4.8 lacks many dynamic link libraries, such as mpi/libldl/libm/libstdc++ etc.. What could be the reason for such differences in the linked libraries resolved in the same environment?

**Comment by stefanozampini** [comment]
`petsc_libraries_external` is populated depending on some tests https://github.com/mfem/mfem/blob/master/config/cmake/modules/FindPETSc.cmake#L312, while `petsc_libs_external` is read directly from PETSc configuration https://github.com/mfem/mfem/blob/master/config/cmake/modules/FindPETSc.cmake#L177

This seems to be an inconsistency in the glibc used, maybe you upgraded the compiler in between PETSc compilation and the new MFEM build? Can you try reinstalling PETSc and see if the issue persists?

**Comment by luanmingyi** [comment]
I’ve just updated the description of the issue, including the debugging process I went through. I now suspect it might be related to CMP0126. If I set this policy to OLD, the configuration passes. Haven’t you encountered the same issue in your tests?

**Comment by chapman39** [comment]
i've run into this error was well

**Comment by chapman39** [comment]
unfortunately, since cmake_minimum_required updates the policy values, using this variable doesn't work when calling mfem as a subdirectory https://cmake.org/cmake/help/latest/variable/CMAKE_POLICY_DEFAULT_CMPNNNN.html#variable:CMAKE_POLICY_DEFAULT_CMP%3CNNNN%3E

The only way i've been able to get around this is by manually updating the policy within MFEM's cmake lists after cmake_minimum has been set.

**Comment by tzanio** [comment]
Discussion continued in #4806
