### ISSUE TITLE
general\zstr.hpp:68:8: error: 'strerror_s' was not declared in this scope

### ISSUE THREAD

**Issue by ghost** [mfem/mfem#1820]
Hi,

Trying to build with cmake 3.15.6 and compiling with g++ 9.2.0 under Win 10 and got this error.  The cmake config command is:
`cmake -DCMAKE_MAKE_PROGRAM=make -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" ..`
Is strerror_s compiler specified function (say ms-VC)?

Cheers

Henry

**Comment by jandrej** [comment]
Can you clarify what you mean by g++ under Win10? Are you using WSL?

**Comment by v-dobrev** [comment]
It looks like the `#ifdef` here: https://github.com/mfem/mfem/blob/f97eef13fce98d86ab5d3a1a9e163f82204b3f88/general/zstr.hpp#L67-L72
needs to use `_MSC_VER` instead of `_WIN32`.

**Comment by henrywoods95** [comment]
> Can you clarify what you mean by g++ under Win10? Are you using WSL?

No WSL. I am using gnu c++ from here http://www.equation.com/servlet/equation.cmd?fa=fortran
