### ISSUE TITLE
MPI_Session is an MPI 4.0 handle

### ISSUE THREAD

**Issue by raffenet** [mfem/mfem#2957]
It appears that `MPI_Session` is used in `general/communication.hpp` as a class name. MPI 4.0 added `MPI_Session` as a standard MPI handle type. Spack E4S builds with MPICH versions >= 4.0 fail because of the ambiguity.

https://github.com/mfem/mfem/blob/168b19fc4904dc90e217bef9b5c3f595c4865da2/general/communication.hpp#L90-L104

```
ex1p.cpp(66): error: "MPI_Session" is ambiguous
1 error detected in the compilation of "ex1p.cpp".
makefile:78: recipe for target 'ex1p' failed
make: *** [ex1p] Error 1
make: Leaving directory '/tmp/root/spack-stage/spack-stage-mfem-4.3.0-eh3uxmai2x52ienouug4aiftaydipfd6/spack-src/examples'
```

**Comment by tzanio** [comment]
Hi @raffenet,

Do you know if this failure is specific to new mfem-4.4?

I am asking because `MPI_Session` has been in MFEM for quite a few years and while we did some refactoring in mfem-4.4, we maintained it for backward compatability.

Thanks,
Tzanio

**Comment by v-dobrev** [comment]
This error is probably from MFEM version < 4.40. In 4.4.0, `MPI_Session` was replaced by `Mpi::Init()` in most examples and miniapps.

Also, one can probably just continue to use `MPI_Session` by adding the namespace qualifier,`mfem::MPI_Session`, unless, `MPI_Session` can be a macro in MPI v4?

**Comment by v-dobrev** [comment]
By the way, @raffenet, I'm close to completing the addition of MFEM v4.4.0 to Spack: https://github.com/spack/spack/pull/29658 which may help resolve the issue if E4S uses the default MFEM version from Spack.

**Comment by raffenet** [comment]
> This error is probably from MFEM version < 4.4.0. In 4.4.0, `MPI_Session` was replaced by `Mpi::Init()` in most examples and miniapps.
> 
> Also, one can probably just continue to use `MPI_Session` by adding the namespace qualifier,`mfem::MPI_Session`, unless, `MPI_Session` can be a macro in MPI v4?

MPI_Session is just an opaque type. In MPICH it is typedef'd to int in mpi.h.

**Comment by v-dobrev** [comment]
Addressed in #3040.
