### ISSUE TITLE
How can I determinate a numerical solution in any points (x,y) ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1351]
Hello !

After a simulation, I would like to know how can I determinate a numerical solution in any points (x,y) ?
Let's name my solution "phi". 
To know the solution at each nodes, I can use  :  phi.NodalValues(...,1).

But now, I would like to have numerical solutions in differents points (x,y) that I chose (in my domain). How can I do that ? Is there something else similar to ".NodalValues" for that?

Best,

Leïla

**Comment by vladotomov** [comment]
Hi Leila,
Example for interpolation of FE solution in physical space can be found in /miniapps/gslib/findpts.cpp.
Good luck,
Vladimir

**Comment by v-dobrev** [comment]
Another option that may work for you is the method `Mesh::FindPoints` -- it does not require GSLIB but it is not 100% reliable. The input consists of points in physical space and the output gives element ids and reference point locations. Given those you can evaluate your solution using methods like `GridFunction::GetValue` which takes element id and reference point location.

Actually there is also a miniapp for that -- see `miniapps/tools/get-values.cpp`.

**Comment by LeilaSalomon** [comment]
> Hi Leila,
> Example for interpolation of FE solution in physical space can be found in /miniapps/gslib/findpts.cpp. This example requires building with GSLIB.
> Good luck,
> Vladimir

Hello Vladimir,

Currently I'm working with the the mfem-3.4 version, and gslib doesn't exist... I'm trying to install the last release "mfem-4.1" but the compilation doesn't work... Should it be installed differently from the 3-4 version ?

Best,

Leïla

**Comment by vladotomov** [comment]
GSLIB must be installed as an external library, eg from [here](https://github.com/Nek5000/gslib), on the same level as mfem's directory. Then mfem must be built by setting `MFEM_USE_GSLIB=YES` in your `config/user.mk`. Let us know if something doesn't work.

Vladimir

**Comment by tzanio** [comment]
There is also some description in the `INSTALL` file of mfem-4.1. If there are build errors, please post them here.

**Comment by LeilaSalomon** [comment]
> GSLIB must be installed as an external library, eg from [here](https://github.com/Nek5000/gslib), on the same level as mfem's directory. Then mfem must be built by setting `MFEM_USE_GSLIB=YES` in your `config/user.mk`. Let us know if something doesn't work.
> 
> Vladimir

If I use the 4.1 version, is it necessary to install GSLIB like an external library ? Because there is a folder "gslib" in miniapps.

**Comment by tzanio** [comment]
> If I use the 4.1 version, is it necessary to install GSLIB like an external library ? Because there is a folder "gslib" in miniapps.

Yes it is. The `miniapps/gslib` folder is for small examples of how to use the gslib integration in mfem

**Comment by LeilaSalomon** [comment]
> > If I use the 4.1 version, is it necessary to install GSLIB like an external library ? Because there is a folder "gslib" in miniapps.
> 
> Yes it is. The `miniapps/gslib` folder is for small examples of how to use the gslib integration in mfem

Ok thank you, I install GSLIB in the same folder as MFEM and I add "MFEM_USE_GSLIB=YES" in  "config.mk". 
But, how compile GSLIB ?

**Comment by v-dobrev** [comment]
Just to clarify -- you can build MFEM 4.1 without GSLIB -- you need GSLIB only if you want to use things that depend on it like the miniapps in `miniapps/gslib`. The other miniapp, that I mentioned previously, `get-values`,  in `miniapps/tools`, does not need GSLIB.

**Comment by LeilaSalomon** [comment]
> Just to clarify -- you can build MFEM 4.1 without GSLIB -- you need GSLIB only if you want to use things that depend on it like the miniapps in `miniapps/gslib`. The other miniapp, that I mentioned previously, `get-values`, in `miniapps/tools`, does not need GSLIB.

Yes thanks, I understood that well

**Comment by kmittal2** [comment]
> > > If I use the 4.1 version, is it necessary to install GSLIB like an external library ? Because there is a folder "gslib" in miniapps.
> > 
> > 
> > Yes it is. The `miniapps/gslib` folder is for small examples of how to use the gslib integration in mfem
> 
> Ok thank you, I install GSLIB in the same folder as MFEM and I add "MFEM_USE_GSLIB=YES" in "config.mk".
> But, how compile GSLIB ?

To compile `gslib`, go inside the `gslib` folder and use  `make CC=gcc MPI=0` for `serial` and `make CC=mpicc MPI=1` for parallel build. Next, you go back to the MFEM folder and build MFEM as `make serial -j MFEM_USE_GSLIB=YES` or `make parallel -j MFEM_USE_GSLIB=YES`.

**Comment by LeilaSalomon** [comment]
> > > > If I use the 4.1 version, is it necessary to install GSLIB like an external library ? Because there is a folder "gslib" in miniapps.
> > > 
> > > 
> > > Yes it is. The `miniapps/gslib` folder is for small examples of how to use the gslib integration in mfem
> > 
> > 
> > Ok thank you, I install GSLIB in the same folder as MFEM and I add "MFEM_USE_GSLIB=YES" in "config.mk".
> > But, how compile GSLIB ?
> 
> To compile `gslib`, go inside the `gslib` folder and use `make CC=gcc MPI=0` for `serial` and `make CC=mpicc MPI=1` for parallel build. Next, you go back to the MFEM folder and build MFEM as `make serial -j MFEM_USE_GSLIB=YES` or `make parallel -j MFEM_USE_GSLIB=YES`.

Ok thank you, and is it possible to use it with the 3-4 version ?

**Comment by kmittal2** [comment]
I believe not. gslib functionality was introduced in 4.1.

**Comment by LeilaSalomon** [comment]
> I believe not. gslib functionality was introduced in 4.1.

Ok thank you, and I don't know why but I can't use this version... 
Is there a particular way to install/compile the 4.1 version ? Or can I install/compile in the same way as 3.4 ?

**Comment by kmittal2** [comment]
What is the error that you get when you compile? Do you intend to use `gslib` with `MFEM` in `serial` or `parallel`?

**Comment by LeilaSalomon** [comment]
> What is the error that you get when you compile? Do you intend to use `gslib` with `MFEM` in `serial` or `parallel`?

I would like to use them in serial. First , I untar and compile gslib in the same level as mfem-4.1, second I compile mfem-4.1 with "make serial -j MFEM_USE_GSLIB=YES", but there are erros : gslib files are not found. 
For exemple, I have "   error : gslib.h : no such file or folder #include "gslib.h"   " (it's the same for the other files)

**Comment by kmittal2** [comment]
I see that we didn't mention this above. As per INSTALL, once you download and build `gslib`, you should use `ln -s gslib-1.0.5 gslib` at the same level as MFEM. Let me know if you still get compilation errors after you do this.

**Comment by LeilaSalomon** [comment]
> I see that we didn't mention this above. As per INSTALL, once you download and build `gslib`, you should use `ln -s gslib-1.0.5 gslib` at the same level as MFEM. Let me know if you still get compilation errors after you do this.

Thank you so much !!!
Now, when I try to compile a code, I have hundreds of error lines (which I didn't have with version 3.4!). Can't I compile both versions in the same way ?

**Comment by LeilaSalomon** [comment]
> > I see that we didn't mention this above. As per INSTALL, once you download and build `gslib`, you should use `ln -s gslib-1.0.5 gslib` at the same level as MFEM. Let me know if you still get compilation errors after you do this.
> 
> Thank you so much !!!
> Now, when I try to compile a code, I have hundreds of error lines (which I didn't have with version 3.4!). Can't I compile both versions in the same way ?

Oh.. forget this question, I forgot to specify the C++ version, so the library could not be read...

**Comment by LeilaSalomon** [comment]
Thank you for your help !! I'm able to run the exemple "findpts" with mfem and gslib ! This is exactly the example I was looking for to solve my problem ! 

I just have one last question, I don't know how to configure the "finder.Setup()" for a tetrahedral mesh. This only works for a quadratic mesh...

**Comment by kmittal2** [comment]
You should have support for simplices with findpts within the next few days. See [PR#1304](https://github.com/mfem/mfem/pull/1304), which will likely be merged this weekend.
